nfc: nq-nci{pnt80t}: Disable unused is_data_available_for_read function
nfc/nq-nci-pn80t.c:155:12: error: unused function 'is_data_available_for_read' [-Werror,-Wunused-function]
static int is_data_available_for_read(struct nqx_dev *nqx_dev)
           ^