msm: camera_v3: icp: fix -Wunsequenced
Fixes:
drivers/media/platform/msm/camera/cam_icp/icp_hw/icp_hw_mgr/cam_icp_hw_mgr.c:3481:17:
error: multiple unsequenced modifications to 'num_cmd_buf'
[-Werror,-Wunsequenced]
num_cmd_buf-- : 0;
           ^
drivers/media/platform/msm/camera/cam_icp/icp_hw/icp_hw_mgr/cam_icp_hw_mgr.c:3505:17:
error: multiple unsequenced modifications to 'num_cmd_buf'
[-Werror,-Wunsequenced]
num_cmd_buf-- : 0;
           ^

This code is decrementing num_cmd_buf, but clamping it at 0.

See:
commit 05349feaa2032 ("Camera: Bring over camera driver changes")
to techpack/camera/drivers/cam_icp/icp_hw/icp_hw_mgr/cam_icp_hw_mgr.c
in newer device's kernels.

Bug: 155426751
Signed-off-by: Nick Desaulniers <ndesaulniers@google.com>
Change-Id: Ib55cd21f9298c125294d55837dc96bff9d7bc9e7
Signed-off-by: UtsavBalar1231 <utsavbalar1231@gmail.com>