exfat: Include a missing header
- This fixes the following error:

../fs/exfat/balloc.c: In function 'exfat_trim_fs':
../fs/exfat/balloc.c:320:21: error: implicit declaration of function 'fatal_signal_pending' [-Werror=implicit-function-declaration]
  320 |                 if (fatal_signal_pending(current)) {
      |                     ^~~~~~~~~~~~~~~~~~~~
cc1: some warnings being treated as errors

Signed-off-by: Cyber Knight <cyberknight755@gmail.com>