fixup! 53b45ef BACKPORT: pstore/ram: Introduce max_reason and convert… … dump_oops
../fs/pstore/ram.c:1023:15: error: no member named 'dump_oops' in 'struct ramoops_platform_data'
        ramoops_data.dump_oops = 1;
        ~~~~~~~~~~~~ ^
1 error generated.